export type WorkOrderType = {
  report_id: number;
  tenantId: number;
  wo_number: string;
  org_wo_num: number;
  wo_status: string;
  client_company_alias: string;
  cust_text: string;
  loan_number: string;
  loan_type_other: string;
  date_received: string;
  date_due: string;
  start_date: string;
  address: string;
  city?: string;
  state: string;
  zip: string;
  comments: string;
  work_type_alias: string;
  mortgage_name: string;
  ppw_report_id: number;
  import_user_id?: string;
  mcs_woid: string;
  bg_checkin_provider: string;
  autoimport_client_orig: string;
  wo_number_orig: string;
  wo_photo_ts_format: string;
  autoimport_userid: string;
  lot_size: string;
  lock_code: string;
  key_code: string;
  broker_name: string;
  broker_company: string;
  broker_phone: string;
  broker_email: string;
  has_foh: boolean;
  coordinates?: string;

  createdAt?: Date;
  updatedAt?: Date;
};

